name: "Kenneth Hanson - Michigan State University"
shortname: "Kenneth Hanson"
description: "Kenneth Hanson's MSU Homepage"

baseurl: "/"

permalink: pretty
highlighter: pygments

markdown: rdiscount
rdiscount:
  extensions: [smart]
