name: "Kenneth Hanson - Michigan State University"
shortname: "Kenneth Hanson"
description: "Kenneth Hanson's MSU Homepage"

baseurl: "/~hanson54"

permalink: pretty
highlighter: pygments

markdown: rdiscount
rdiscount:
  extensions: [smart]

ftp_host: 'afs.msu.edu'
ftp_dir: '/afs/msu/user/h/a/hanson54/web'
ftp_passive: false